apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
  AIRTABLE_API_KEY: {{ .Values.secrets.AIRTABLE_API_KEY }}
  AIRTABLE_BASE_ID: {{ .Values.secrets.AIRTABLE_BASE_ID }}
  EC2_INSTANCES_TID: {{ .Values.secrets.EC2_INSTANCES_TID }}
  EC2_SECURITY_GROUPS_TID: {{ .Values.secrets.EC2_SECURITY_GROUPS_TID }}